package com.isfootball.jdbc;

import com.isfootball.parser.BetSite;
import org.springframework.data.domain.Persistable;
import org.apache.commons.lang.builder.ToStringBuilder;
import java.util.Date;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
public class Bet implements Persistable<Long>
{

	private static final long serialVersionUID = 1L;

	private Long id;

	private Long matchId;

	private String bet;

	private Double betVal;

	private String site;

	private Date dateAdded = new Date ();

	private Date updated;

	private transient boolean persisted;

	//
	private BetSite betSite;

	public Bet()
	{

	}

	public Long getId ()
	{
		return this.id;
	}

	public boolean isNew ()
	{
		return this.id == null;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public void setMatchId (Long matchId)
	{
		this.matchId = matchId;
	}

	public Long getMatchId ()
	{
		return this.matchId;
	}

	public void setBet (String bet)
	{
		this.bet = bet;
	}

	public String getBet ()
	{
		return this.bet;
	}

	public void setBetVal (Double betVal)
	{
		this.betVal = betVal;
	}

	public Double getBetVal ()
	{
		return this.betVal;
	}

	public void setSite (String site)
	{
		this.site = site;
		this.betSite = BetSite.valueOf(site);
	}

	public String getSite ()
	{
		return this.site;
	}

	public void setDateAdded (Date dateAdded)
	{
		this.dateAdded = dateAdded;
	}

	public Date getDateAdded ()
	{
		return this.dateAdded;
	}

	public void setUpdated (Date updated)
	{
		this.updated = updated;
	}

	public Date getUpdated ()
	{
		return this.updated;
	}

	public void setPersisted (Boolean persisted)
	{
		this.persisted = persisted;
	}

	public Boolean getPersisted ()
	{
		return this.persisted;
	}

	@Override
	public String toString () 
	{
		return ToStringBuilder.reflectionToString (this); 
	}

	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	public BetSite getBetSite() {
		return betSite;
	}

	public void setBetSite(BetSite betSite) {
		this.betSite = betSite;
	}
}