package com.isfootball.jdbc;

import org.springframework.data.domain.Persistable;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
public class BetTypes implements Persistable<String>
{

	private static final long serialVersionUID = 1L;

	private String bet;

	private String betRus;

	private transient boolean persisted;


	public BetTypes ()
	{

	}

	public String getId ()
	{
		return this.bet;
	}

	public boolean isNew ()
	{
		return this.bet == null;
	}

	public void setBet (String bet)
	{
		this.bet = bet;
	}

	public String getBet ()
	{
		return this.bet;
	}

	public void setBetRus (String betRus)
	{
		this.betRus = betRus;
	}

	public String getBetRus ()
	{
		return this.betRus;
	}

	public void setPersisted (Boolean persisted)
	{
		this.persisted = persisted;
	}

	public Boolean getPersisted ()
	{
		return this.persisted;
	}

	@Override
	public String toString () 
	{
		return ToStringBuilder.reflectionToString (this); 
	}

	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}