package com.isfootball.jdbc;

import org.springframework.data.domain.Persistable;
import org.apache.commons.lang.builder.ToStringBuilder;
import java.util.Date;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
public class SiteUpdates implements Persistable<Long>
{

	private static final long serialVersionUID = 1L;

	private Long id;

	private String site;

	private Date dateAdded = new Date ();

	private Integer eventsNumber;

	private Integer updateTime;

	private transient boolean persisted;


	public SiteUpdates ()
	{

	}

	public Long getId ()
	{
		return this.id;
	}

	public boolean isNew ()
	{
		return this.id == null;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public void setSite (String site)
	{
		this.site = site;
	}

	public String getSite ()
	{
		return this.site;
	}

	public void setDateAdded (Date dateAdded)
	{
		this.dateAdded = dateAdded;
	}

	public Date getDateAdded ()
	{
		return this.dateAdded;
	}

	public void setEventsNumber (Integer eventsNumber)
	{
		this.eventsNumber = eventsNumber;
	}

	public Integer getEventsNumber ()
	{
		return this.eventsNumber;
	}

	public void setUpdateTime (Integer updateTime)
	{
		this.updateTime = updateTime;
	}

	public Integer getUpdateTime ()
	{
		return this.updateTime;
	}

	public void setPersisted (Boolean persisted)
	{
		this.persisted = persisted;
	}

	public Boolean getPersisted ()
	{
		return this.persisted;
	}

	@Override
	public String toString () 
	{
		return ToStringBuilder.reflectionToString (this); 
	}

	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}