package com.isfootball.jdbc.rep;

import com.nurkiewicz.jdbcrepository.JdbcRepository;
import org.springframework.stereotype.Repository;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;
import com.isfootball.jdbc.rep.db.BetSitesDB;
import com.isfootball.jdbc.BetSites;
import org.springframework.jdbc.core.RowMapper;
import com.nurkiewicz.jdbcrepository.RowUnmapper;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
@Repository
public class BetSitesRepository extends JdbcRepository<BetSites, String>
{

	final static Logger logger = LoggerFactory.getLogger (BetSitesRepository.class);

	public BetSitesRepository()
	{
		super (BetSitesDB.ROW_MAPPER, BetSitesDB.ROW_UNMAPPER, BetSitesDB.getTableName ());
	}

	public BetSitesRepository(RowMapper<BetSites> rowMapper, RowUnmapper<BetSites> rowUnmapper, String idColumn)
	{
		super (BetSitesDB.ROW_MAPPER, BetSitesDB.ROW_UNMAPPER, BetSitesDB.getTableName (), idColumn);
	}

	@Override
	protected BetSites postCreate(BetSites entity, Number generatedId)
	{
		entity.setPersisted(true);
		return entity;
	}



	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}

