package com.isfootball.jdbc.rep;

import com.isfootball.jdbc.Bet;
import com.nurkiewicz.jdbcrepository.JdbcRepository;
import org.springframework.stereotype.Repository;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;
import com.isfootball.jdbc.rep.db.BetsDB;
import org.springframework.jdbc.core.RowMapper;
import com.nurkiewicz.jdbcrepository.RowUnmapper;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
@Repository
public class BetsRepository extends JdbcRepository<Bet, Long>
{

	final static Logger logger = LoggerFactory.getLogger (BetsRepository.class);

	public BetsRepository()
	{
		super (BetsDB.ROW_MAPPER, BetsDB.ROW_UNMAPPER, BetsDB.getTableName ());
	}

	public BetsRepository(RowMapper<Bet> rowMapper, RowUnmapper<Bet> rowUnmapper, String idColumn)
	{
		super (BetsDB.ROW_MAPPER, BetsDB.ROW_UNMAPPER, BetsDB.getTableName (), idColumn);
	}

	@Override
	protected Bet postCreate(Bet entity, Number generatedId)
	{
		entity.setId(generatedId.longValue());
		entity.setPersisted(true);
		return entity;
	}



	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}

