package com.isfootball.jdbc.rep;

import com.nurkiewicz.jdbcrepository.JdbcRepository;
import org.springframework.stereotype.Repository;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;
import com.isfootball.jdbc.rep.db.BetTypesDB;
import com.isfootball.jdbc.BetTypes;
import org.springframework.jdbc.core.RowMapper;
import com.nurkiewicz.jdbcrepository.RowUnmapper;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
@Repository
public class BetTypesRepository extends JdbcRepository<BetTypes, String>
{

	final static Logger logger = LoggerFactory.getLogger (BetTypesRepository.class);

	public BetTypesRepository()
	{
		super (BetTypesDB.ROW_MAPPER, BetTypesDB.ROW_UNMAPPER, BetTypesDB.getTableName ());
	}

	public BetTypesRepository(RowMapper<BetTypes> rowMapper, RowUnmapper<BetTypes> rowUnmapper, String idColumn)
	{
		super (BetTypesDB.ROW_MAPPER, BetTypesDB.ROW_UNMAPPER, BetTypesDB.getTableName (), idColumn);
	}

	@Override
	protected BetTypes postCreate(BetTypes entity, Number generatedId)
	{
		entity.setPersisted(true);
		return entity;
	}



	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}

