package com.isfootball.jdbc.rep;

import com.nurkiewicz.jdbcrepository.JdbcRepository;
import org.springframework.stereotype.Repository;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;
import com.isfootball.jdbc.rep.db.MatchesDB;
import com.isfootball.jdbc.Match;
import org.springframework.jdbc.core.RowMapper;
import com.nurkiewicz.jdbcrepository.RowUnmapper;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
@Repository
public class MatchesRepository extends JdbcRepository<Match, Long>
{

	final static Logger logger = LoggerFactory.getLogger (MatchesRepository.class);

	public MatchesRepository()
	{
		super (MatchesDB.ROW_MAPPER, MatchesDB.ROW_UNMAPPER, MatchesDB.getTableName ());
	}

	public MatchesRepository(RowMapper<Match> rowMapper, RowUnmapper<Match> rowUnmapper, String idColumn)
	{
		super (MatchesDB.ROW_MAPPER, MatchesDB.ROW_UNMAPPER, MatchesDB.getTableName (), idColumn);
	}

	@Override
	protected Match postCreate(Match entity, Number generatedId)
	{
		entity.setId(generatedId.longValue());
		entity.setPersisted(true);
		return entity;
	}



	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}

