package com.isfootball.jdbc.rep;

import com.nurkiewicz.jdbcrepository.JdbcRepository;
import org.springframework.stereotype.Repository;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;
import com.isfootball.jdbc.rep.db.SiteUpdatesDB;
import com.isfootball.jdbc.SiteUpdates;
import org.springframework.jdbc.core.RowMapper;
import com.nurkiewicz.jdbcrepository.RowUnmapper;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
@Repository
public class SiteUpdatesRepository extends JdbcRepository<SiteUpdates, Long>
{

	final static Logger logger = LoggerFactory.getLogger (SiteUpdatesRepository.class);

	public SiteUpdatesRepository()
	{
		super (SiteUpdatesDB.ROW_MAPPER, SiteUpdatesDB.ROW_UNMAPPER, SiteUpdatesDB.getTableName ());
	}

	public SiteUpdatesRepository(RowMapper<SiteUpdates> rowMapper, RowUnmapper<SiteUpdates> rowUnmapper, String idColumn)
	{
		super (SiteUpdatesDB.ROW_MAPPER, SiteUpdatesDB.ROW_UNMAPPER, SiteUpdatesDB.getTableName (), idColumn);
	}

	@Override
	protected SiteUpdates postCreate(SiteUpdates entity, Number generatedId)
	{
		entity.setId(generatedId.longValue());
		entity.setPersisted(true);
		return entity;
	}



	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}

