package com.isfootball.jdbc.rep;

import com.nurkiewicz.jdbcrepository.JdbcRepository;
import org.springframework.stereotype.Repository;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;
import com.isfootball.jdbc.rep.db.TeamsDB;
import com.isfootball.jdbc.Teams;
import org.springframework.jdbc.core.RowMapper;
import com.nurkiewicz.jdbcrepository.RowUnmapper;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
@Repository
public class TeamsRepository extends JdbcRepository<Teams, String>
{

	final static Logger logger = LoggerFactory.getLogger (TeamsRepository.class);

	public TeamsRepository()
	{
		super (TeamsDB.ROW_MAPPER, TeamsDB.ROW_UNMAPPER, TeamsDB.getTableName ());
	}

	public TeamsRepository(RowMapper<Teams> rowMapper, RowUnmapper<Teams> rowUnmapper, String idColumn)
	{
		super (TeamsDB.ROW_MAPPER, TeamsDB.ROW_UNMAPPER, TeamsDB.getTableName (), idColumn);
	}

	@Override
	protected Teams postCreate(Teams entity, Number generatedId)
	{
		entity.setPersisted(true);
		return entity;
	}



	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}

