package com.isfootball.jdbc.rep.db;

import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import java.sql.ResultSet;
import java.util.LinkedHashMap;
import java.util.Map;
import com.nurkiewicz.jdbcrepository.RowUnmapper;
import com.isfootball.jdbc.BetSites;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
public class BetSitesDB
{

	private static String TABLE_NAME = "BET_SITES";

	private static String TABLE_ALIAS = "bs";

	public static String getTableName()
	{
		return TABLE_NAME;
	}

	public static String getTableAlias()
	{
		return TABLE_NAME + " as " + TABLE_ALIAS;
	}

	public static String getAlias()
	{
		return TABLE_ALIAS;
	}

	public static String selectAllColumns(boolean ... useAlias)
	{
		return (useAlias[0] ? TABLE_ALIAS : TABLE_NAME) + ".*";
	}

	public enum COLUMNS
	{
		SITE("site"),
		URL("url"),
		COMMENTS("comments"),
		;

		private String columnName;

		private COLUMNS (String columnName)
		{
			this.columnName = columnName;
		}

		public void setColumnName (String columnName)
		{
			this.columnName = columnName;
		}

		public String getColumnName ()
		{
			return this.columnName;
		}

		public String getColumnAlias ()
		{
			return TABLE_ALIAS + "." + this.columnName;
		}

		public String getColumnAliasAsName ()
		{
			return TABLE_ALIAS  + "." + this.columnName + " as " + TABLE_ALIAS + "_" + this.columnName;
		}

		public String getColumnAliasName ()
		{
			return TABLE_ALIAS + "_" + this.columnName;
		}

	}

	public BetSitesDB ()
	{

	}

	public static final RowMapper<BetSites> ROW_MAPPER = new BetSitesRowMapper ();
	public static final class  BetSitesRowMapper implements RowMapper<BetSites>
	{
		public BetSites mapRow(ResultSet rs, int rowNum) throws SQLException 
		{
			BetSites obj = new BetSites();
			obj.setSite(rs.getString(COLUMNS.SITE.getColumnName()));
			obj.setUrl(rs.getString(COLUMNS.URL.getColumnName()));
			obj.setComments(rs.getString(COLUMNS.COMMENTS.getColumnName()));
			return obj;
		}
	}

	public static final RowUnmapper<BetSites> ROW_UNMAPPER = new BetSitesRowUnmapper ();
	public static final class BetSitesRowUnmapper implements RowUnmapper<BetSites>
	{
		public Map<String, Object> mapColumns(BetSites betsites)
		{
			Map<String, Object> mapping = new LinkedHashMap<String, Object>();
			mapping.put(COLUMNS.SITE.getColumnName(), betsites.getSite());
			mapping.put(COLUMNS.URL.getColumnName(), betsites.getUrl());
			mapping.put(COLUMNS.COMMENTS.getColumnName(), betsites.getComments());
			return mapping;
		}
	}

	public static final RowMapper<BetSites> ALIAS_ROW_MAPPER = new BetSitesAliasRowMapper ();
	public static final class  BetSitesAliasRowMapper implements RowMapper<BetSites>
	{
		public BetSites mapRow(ResultSet rs, int rowNum) throws SQLException 
		{
			BetSites obj = new BetSites();
			obj.setSite(rs.getString(COLUMNS.SITE.getColumnAliasName()));
			obj.setUrl(rs.getString(COLUMNS.URL.getColumnAliasName()));
			obj.setComments(rs.getString(COLUMNS.COMMENTS.getColumnAliasName()));
			return obj;
		}
	}

	public static StringBuffer getAllColumnAliases ()
	{
		StringBuffer strBuf = new StringBuffer ();
		int i = COLUMNS.values ().length;
		for (COLUMNS c : COLUMNS.values ())
		{
			strBuf.append (c.getColumnAliasAsName ());
			if (--i > 0)
				strBuf.append (", ");
		}
		return strBuf;
	}

	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}